### ISSUE TITLE
Toolkit

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#55] opened 2022-12-01 17:59 UTC
Right now in the documentation the recommended way to install the toolkit is the following:
```
npx @massalabs/sc-toolkit init my-sc
```
Currently, trying to build the helloworld SC returns the following error:
```
➜  ~/dev/massa-sc-examples/blog/my-sc (base) (massa-blog) ✗ npm run build                                                             127

> my-massa-sc@1.0.0 build
> asc assembly/index.ts --target release --exportRuntime -o build/index.wasm && asc --transform transformer/file2base64.js assembly/main.ts --target release --exportRuntime -o build/main.wasm

ERROR TS2322: Type '~lib/string/String' is not assignable to type '~lib/staticarray/StaticArray<u8>'.
   :
 6 │ Storage.set('key', 'value');
   │             ~~~~~
   └─ in assembly/index.ts(6,14)

ERROR TS2322: Type '~lib/string/String' is not assignable to type '~lib/staticarray/StaticArray<u8>'.
   :
 6 │ Storage.set('key', 'value');
   │                    ~~~~~~~
   └─ in assembly/index.ts(6,21)

FAILURE 2 compile error(s)
```

Either we should keep the doc with a versioned toolkit that we update regularly or make sure that the main branch never has errors.

Let's take https://github.com/massalabs/massa-sc-toolkit/issues/60 as the opportunity to tackle this issue as well.

cc @longgamma-massa @SlnPons

**Comment by Thykof** [comment] 2022-12-02 13:54
Today the documentation does not need to be updated. The toolkit is broken because it targets <https://test.massa.net/api/v2> and it has not been updated to testnet17 yet (https://github.com/massalabs/massa-sc-toolkit/pull/61). 

If we want the documentation to be always working, we will need a stable RPC URL (e.g. localhost) and a version of the toolkit for each version of testnet, and in the documentation target the latest working version of the toolkit.

**Comment by qdrn** [comment] 2022-12-02 14:22
I don't get your answer. The build should work regardless of the target for the deployment.

That being said, I think it's important to have as little as possible "downtime" and keep the toolkit as synced as possible with the latest version of the testnet. This will be easier as time goes on as the number of features being developed that are breaking are reducing.

**Comment by Thykof** [comment] 2022-12-05 08:01
The build command don't work because the toolkit depends on massa-as-sdk version flagged dev. A dev version is released at each push on main. So to fix the build command we can target a specific previous version of the massa-as-sdk. But the deploy command won't work on testnet17.

**Comment by qdrn** [comment] 2022-12-05 11:21
> The build command don't work because the toolkit depends on massa-as-sdk version flagged dev. A dev version is released at each push on main.

I understand that. However it defeats the purpose of having a documentation if the commands in the documentation are not working.

Having everything working all the time is probably hard to achieve when a lot of breaking features are added to Massa. However, we should try to have as much feature working as possible. In the case of the build command it's probably simpler to achieve as it does not depend on the node version. We can ensure that at the toolkit level.

Then again, this issue can be tackled either by pointing to a tagged version of the toolkit or ensuring that the main branch of the toolkit is always working.

**Comment by gregLibert** [comment] 2022-12-05 14:57
From what I understand, the error comes from an incompatibility between the library used and the code provided as an example.
It's indeed something that we should avoid / can work on.

**Comment by Thykof** [comment] 2022-12-05 15:44
@qdrn could you share with us the source code of the hello world smart contract you used please?

**Comment by peterjah** [comment] 2022-12-05 16:18
it seems your npx command pulls an old version of a toolkit. this file `assembly/index.ts` has been deleted 3 weeks ago by commit 96ea292

**Comment by peterjah** [comment] 2022-12-05 16:19
clearing the npx cache solved the issue for me. but i guess we have to investigate it anyway

**Comment by Thykof** [comment] 2022-12-23 10:00
I have made some test, `npx` always takes the latest version even if it has an old one in cache. but what I can't reproduce is when on Monday you use the command, on Tuesday inno team publish a new version, on Wednesday you use the command, it will take the the Monday's version in cache.

**Comment by gregLibert** [comment] 2022-12-30 16:00
@Thykof @peterjah can we reproduce this bug?

**Comment by gregLibert** [comment] 2023-01-04 09:07
The bug is not reproducible buy the inno team devs.
@qdrn can you reproduce it on your side ? If not, I propose to close this issue. We will reopen it later if needed.

**Comment by qdrn** [comment] 2023-01-04 09:37
I have another one now :)
```shell
➜  ~/misc (base) npx @massalabs/sc-toolkit init my-sc
Installation begun...
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adrien/.npm/_logs/2023-01-04T09_36_25_941Z-debug-0.log
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: npm install
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm WARN tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm ERR! code TAR_BAD_ARCHIVE
npm ERR! TAR_BAD_ARCHIVE: Unrecognized archive format

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adrien/.npm/_logs/2023-01-04T09_36_25_941Z-debug-0.log

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at initialize (file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/@massalabs/sc-toolkit/initialize.js:26:5)
    at Object.handler (file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/@massalabs/sc-toolkit/cli.js:24:13)
    at file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/yargs/build/lib/command.js:204:54
    at maybeAsyncResult (file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/yargs/build/lib/command.js:203:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/yargs/build/lib/command.js:243:20)
    at CommandInstance.runCommand (file:///Users/adrien/.npm/_npx/1fb6c64d9f6fb9c7/node_modules/yargs/build/lib/command.js:128:20) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(329) [Uint8Array] [
      110, 112, 109,  32,  87,  65,  82,  78,  32, 116,  97, 114,
       32,  84,  65,  82,  95,  66,  65,  68,  95,  65,  82,  67,
       72,  73,  86,  69,  58,  32,  85, 110, 114, 101,  99, 111,
      103, 110, 105, 122, 101, 100,  32,  97, 114,  99, 104, 105,
      118, 101,  32, 102, 111, 114, 109,  97, 116,  10, 110, 112,
      109,  32,  87,  65,  82,  78,  32, 116,  97, 114,  32,  84,
       65,  82,  95,  66,  65,  68,  95,  65,  82,  67,  72,  73,
       86,  69,  58,  32,  85, 110, 114, 101,  99, 111, 103, 110,
      105, 122, 101, 100,
      ... 229 more items
    ]
  ],
  pid: 3543,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(329) [Uint8Array] [
    110, 112, 109,  32,  87,  65,  82,  78,  32, 116,  97, 114,
     32,  84,  65,  82,  95,  66,  65,  68,  95,  65,  82,  67,
     72,  73,  86,  69,  58,  32,  85, 110, 114, 101,  99, 111,
    103, 110, 105, 122, 101, 100,  32,  97, 114,  99, 104, 105,
    118, 101,  32, 102, 111, 114, 109,  97, 116,  10, 110, 112,
    109,  32,  87,  65,  82,  78,  32, 116,  97, 114,  32,  84,
     65,  82,  95,  66,  65,  68,  95,  65,  82,  67,  72,  73,
     86,  69,  58,  32,  85, 110, 114, 101,  99, 111, 103, 110,
    105, 122, 101, 100,
    ... 229 more items
  ]
}

Node.js v18.11.0
```

**Comment by peterjah** [comment] 2023-01-04 13:19
The root cause of all these issues is because we use npx. It download the toolkit in a temp directory of npm or use a cached one and do the "init" command with it. Thus we face issue because we dont really knwo wich versions its uses and we have also issue with cached old versions.
Imho the clean way of doing it would be to install the package globally with npm 
`npm install -g @massalabs/sc-toolkit`
this package provide a binary, lets says "massa-sc-cli"
Then we can use `massa-sc-cli init` and we are sure the version does not change

**Comment by qdrn** [comment] 2023-01-04 14:06
Everything was running fine after a `npx clear-npx-cache`.

**Comment by BatiGencho** [comment] 2023-01-05 17:56
That is only on Mac thought :( On Linux I get a lot of problems. Nathan said he knows where the error is and will fix it tomorrow.

**Comment by Thykof** [comment] 2023-01-05 17:57
Yes, the error you encounter has no relation with cache because it's about the new package

**Comment by qdrn** [comment] 2023-01-10 16:58
Since it's broken again I've updated the doc https://github.com/massalabs/massa-docs/commit/9dd1c6bbeb70ed7ae1f1eaa6da6bcffe0e188838. Let's change back once it's working again.

**Closed** 2023-01-13 17:52 UTC
Labels: P2
